# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "messages", :force => true do |t|
    t.column "subject",      :string
    t.column "body",         :text
    t.column "sender_id",    :integer
    t.column "recipient_id", :integer
    t.column "reply_to",     :integer
  end

  create_table "users", :force => true do |t|
    t.column "name", :string
  end

end
